site_name: Black Cat Labs Wiki
theme:
  name: material
  logo: localassets/BLACKCAT-LOGO-BLACK-TRANSPARENT.svg
  favicon: localassets/favicon-32x32.png
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: lime
      accent: cyan
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
    - navigation.indexes
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - attr_list
  - pymdownx.keys:
      separator: +
      strict: false
      camel_case: false
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      enabled: true
      type: date
      fallback_to_build_date: true
      exclude:
        - index.md
  - search
  - awesome-pages
copyright: CC &copy; 2024 Black Cat Labs. This work is openly licensed via CC BY-SA 4.0.