site_name: Black Cat Labs Wiki
theme:
  name: material
  logo: localassets/BLACKCAT-LOGO-WHITE-TRANSPARENT.svg
  favicon: localassets/favicon-32x32.png
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - search.highlight
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.tooltips
    - content.footnote.tooltips
markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - attr_list
  - footnotes
  - toc:
      permalink: true
      permalink_title: Link to this heading
      title: On this page
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - pymdownx.keys:
      separator: +
      strict: false
      camel_case: false
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      enabled: true
      type: date
      fallback_to_build_date: true
      exclude:
        - index.md
  - search
  - awesome-pages
copyright: CC &copy; 2024 | Black Cat Labs LLC. This work is licensed under CC BY-SA 4.0.
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js